name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY_URL }}

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.AWS_ECR_REPOSITORY_URL }}/my-image-name:$(date +%s)

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ECR_REPOSITORY_URL }}/my-image-name:$(date +%s)

    
        